version: '3'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: Blog-app-using-nodejs
    ports:
      - "5000:5000" 
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/blog-app
    image: aravindh/blogger-app-using-nodejs

volumes:
  mongo-data:
  

